@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection
interface Button

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class View&GUI {
JPanel
}

'Button <|-- View&GUI

@enduml